# Generated by Django 4.0.4 on 2022-05-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_rename_passengers_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='lasttName',
            new_name='lastName',
        ),
    ]
